I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapters/chapter3.rpy", line 54, in script call
    call game_104
  File "game/chapters/chapter3.rpy", line 201, in script
    kovaleva "А где конспект?" (what_slow_cps=25)
Exception: Sayer 'kovaleva' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapters/chapter3.rpy", line 54, in script call
    call game_104
  File "game/chapters/chapter3.rpy", line 201, in script
    kovaleva "А где конспект?" (what_slow_cps=25)
  File "C:\Users\zhuma\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\zhuma\renpy-8.3.7-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\zhuma\renpy-8.3.7-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'kovaleva' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
test 1.0
Sun May  4 14:19:03 2025
