I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapters/peremena3.rpy", line 50, in script call
    call peremena3_go
  File "game/chapters/peremena3.rpy", line 57, in script
    $ show_achievement("odin")
  File "game/chapters/peremena3.rpy", line 57, in <module>
    $ show_achievement("odin")
NameError: name 'show_achievement' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapters/peremena3.rpy", line 50, in script call
    call peremena3_go
  File "game/chapters/peremena3.rpy", line 57, in script
    $ show_achievement("odin")
  File "C:\Users\zhuma\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\zhuma\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/chapters/peremena3.rpy", line 57, in <module>
    $ show_achievement("odin")
NameError: name 'show_achievement' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
test 1.0
Sat May 10 12:44:03 2025
